### ISSUE TITLE
Heap Space Issues for Large Inserts

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/cottontaildb#113]
Inserting >10GB of data in one commit causes heap space issues which I did not encounter previously. This is easily avoided client-side, but I'll leave this issue here for future reference.

**Comment by ppanopticon** [comment]
Just out of curiosity: Did this particular INSERT involve an entity with a `LuceneIndex`?

**Comment by silvanheller** [comment]
Seems fixed now
