### ISSUE TITLE
Lucene & limit

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/cottontaildb#123]
Lucene currently does not propagate a limit to the underlying `IndexSearcher`, see:
https://github.com/vitrivr/cottontaildb/blob/ae750e7cb8e10c07681a430f212ca4758e5761e1/cottontaildb-dbms/src/main/kotlin/org/vitrivr/cottontail/dbms/index/lucene/LuceneIndex.kt#L481

This was never noticed because Cineast did not tell cottontail, see: https://github.com/vitrivr/cineast/pull/312

**Comment by ppanopticon** [comment]
This is intended because a `LIMIT` expressed in a query to Cottontail DB cannot always be pushed-down to Lucene (e.g., if we use Lucene to satisfy a predicate and then sort the result based on another column that the index does not cover).

The question is: Is the `LIMIT` respected?

**Comment by silvanheller** [comment]
Limit is respected but not pushed down to the Lucene index, even for simple queries where it would make sense

**Comment by lucaro** [comment]
So this means the result of the query as a whole is correct, but lucene returns unnecessarily many results at an intermediate stage which have to be discarded afterward?

**Comment by silvanheller** [comment]
Yes, this is visible in the logs: 
```
2022-05-17 15:45:44 [DefaultDispatcher-worker-2] DEBUG TransactionalGrpcService:114 - [3414, q-cin-ft-rows-4f8] Preparation of Select completed successfully in 32.095876ms.
2022-05-17 15:45:52 [cottontaildb-query-worker-4] DEBUG IndexScanOperator:70 - Read 428892 entries from warren.cineast.features_audiotranscription.idx_feature_lucene.
2022-05-17 15:45:52 [DefaultDispatcher-worker-2] INFO  TransactionalGrpcService:152 - [3414, q-cin-ft-rows-4f8] Execution of Select completed successfully in 8.392559588s.
```

**Comment by ppanopticon** [comment]
So this is a performance issue I take it? I'll have a look!

**Comment by ppanopticon** [comment]
I have made some changes on `master`. Those do not address the raised issue directly but still iron-out a few glitches, which I suspect to be the culprit. 

Could you quickly test, if there is a performance improvement using that version?

**Comment by silvanheller** [comment]
Much faster, thanks!
