### ISSUE TITLE
Client Query.where not returning matching rows with equality operator

### ISSUE THREAD

**Issue by rasmuswilli** [vitrivr/cottontaildb#135]
`client.query(Query.where(predicate.Expression(column: String, operator: String, value: Any)))` with `operator = "==" or operator = "="` does not return expected rows with column datatypes `BYTE` and `SHORT`. 
`INTEGER`,`LONG`,`FLOAT`,`DOUBLE` work as expected.
This issue has been found using the work in progress UI on the branch `feature/ui`.

![Screenshot 2022-12-02 at 09 56 46](https://user-images.githubusercontent.com/71382521/205254721-21afa05f-2ca6-4468-91ec-6662ea301b82.png)
![Screenshot 2022-12-02 at 09 57 15](https://user-images.githubusercontent.com/71382521/205254799-07276be0-5826-4c11-9666-620ab97817bb.png)

**Comment by lucaro** [comment]
Have you checked that you are not comparing `12` with `"12"`? Those are not the same...

**Comment by rasmuswilli** [comment]
Yes, the Backend of the UI successfully casts values before comparing. @ppanopticon and I checked other possible reasons yesterday.
