### ISSUE TITLE
[Bug][CLI] Create entity with underscore in name makes 🥕 stop working

### ISSUE THREAD

**Issue by sauterl** [vitrivr/cottontaildb#136]
Currently, when creating an entity through 🥕 (`entity create <schema>.<name>`), an interactive entity creator is started.
However, in cases `<name>` contains an underscore (`_`), the interactive creator is not started and 🥕 freezes.
This seems to be an issue with 🥕, since using other means (e.g. application logic) having an underscore in a name is no issue.
In addition, there aren't any error messages printed in cottontaildb

**Comment by ppanopticon** [comment]
I'm afraid I cannot reproduce this. Are you working with the latest version?

Would it be much effort to checkout the current master branch (that's the one I tested this with).

**Comment by sauterl** [comment]
You are right! On branch `master` in a freshly cloned repo I couldn't reproduce this behaviour. My apologies that I didn't try to it out on a fresh setup. I migrated my database to that new one and it works as intended. Closing this issue as apparently, this must have been an artefact of a non-latest build.
