### ISSUE TITLE
Insert performance degrades over time, recovers after restart

### ISSUE THREAD

**Issue by lucaro** [vitrivr/cottontaildb#141]
When inserting many individual entries, the insert performance degrades noticeably over time. After many 10k inserts, it takes about an order of magnitude longer for the same number of writes compared to the beginning. When the insert process is paused, and cottontail is restarted, the performance recovers substantially. This might be related to garbage collection processes performed by xodus. If so, such cleanup should be triggered more often in order to avoid substantial performance degradation.

**Comment by ppanopticon** [comment]
This problem should be (partially) adressed in ``0.16.0``. One reason was the rather inefficient handling auf the auto-incrementing tupleIds.
