### ISSUE TITLE
EQUAL operator does not work for TEXT fields

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/cottontaildb#16]
LIKE gives correct results, = does not

**Comment by lucaro** [comment]
Could you elaborate on what is not correct with the result? Is it empty, incomplete or does it contain invalid entries?

**Comment by silvanheller** [comment]
No results. I assume the query is no propagated to the lucene index, therefore the query does not work (similar to if you had an unoptimized index)

**Comment by lucaro** [comment]
Could you try if removing `|| it.operator == ComparisonOperator.EQUAL` from https://github.com/ppanopticon/cottontaildb/blob/master/src/main/kotlin/ch/unibas/dmi/dbis/cottontail/database/index/lucene/LuceneIndex.kt#L294 helps? Then at least we would know if the problem is with the lucene index...

**Comment by ppanopticon** [comment]
This should have been fixed by now.
