### ISSUE TITLE
Add optional DISTINCT in SELECT

### ISSUE THREAD

**Issue by mpas97** [vitrivr/cottontaildb#20]
It would be great to have the possibility to get distinct values only. Especially when doing batched knns, for instance, we get a lot of duplicates.

**Comment by ppanopticon** [comment]
I just added an experimental implementation. Can you please check if it produces the desired results?

**Comment by mpas97** [comment]
I tried it, but it seems to still return same entries on batched knn.

**Comment by ppanopticon** [comment]
Is there a possibility that you have the same IDs with different distance values? And if yes - do you need the distance information? DINSTINCT currently requires all columns to have different values.

**Comment by mpas97** [comment]
My query selects the id and feature columns only. As I don't request (& receive) more than these two columns I really await distinct values. E.g., requesting a 4*1000 batched knn, the query returns me 4000 times these two columns. Doing a manual id duplicate elimination then, results in 1396 values.

**Comment by mpas97** [comment]
I did some debugging: although I explitely unselect the distance field (i.e. by querying id and feature columns only), the hash function also hashes the distance into the distinct set.

**Comment by mpas97** [comment]
In other words, only hash the fields that are in the SELECT clause.

**Comment by ppanopticon** [comment]
Mhm I tried to reverse the order of projection and DISTINCT; does that solve the problem?

**Comment by mpas97** [comment]
With the same example, I get 1396 rows directly from query now. Great!
And your change makes sense, as doing distinct before projection results in different distances. 👍

**Comment by ppanopticon** [comment]
Not exactly! Projection simply drops the distance column (in case you specified, that you don't need it) before doing the necessary calculations for DISTINCT.

So this works for you then? 

I suppose that this solution is very limited in use especially in cases where you want to keep the distance column and maybe select the smaller value. This would probably be a use case for a GROUP BY like semantic.

**Comment by mpas97** [comment]
Yes, it does. And again, for DISTINCT this is probably what it should do. Because you can always drop some colums and then request the distinct set of values. As you say, getting the minimums of multiple entries etc would be an other "problem" / feature request. This would be some kind of merging functionality rather than distinct.
