### ISSUE TITLE
Add integration tests

### ISSUE THREAD

**Issue by gabuzi** [vitrivr/cottontaildb#22]
I have spotted (by accident) a potential issues with the CosineDistance calculation of complex numbers (see #21). Such issues could be found more quickly with tests.

Additionally, larger tests that use the gRPC endpoints could verify that the whole stack works as intended. With larger datasets, these tests could also serve as an indicator of performance costs of code changes.
Such tests could be:
* Testing of data import
* Testing of a KNN query on the imported data

**Comment by ppanopticon** [comment]
I like the idea of having integration tests that, for example, use the gRPC endpoints, fill it an instance with data and then check if the results of some queries return the correct results.

However, some of the issues (e.g. #21) are probably easier to spot with Unit Tests (see #26).

**Comment by ppanopticon** [comment]
This has been resolved indirectly with the [DQLServiceTest.kt](https://github.com/vitrivr/cottontaildb/blob/master/cottontaildb-dbms/src/test/kotlin/org/vitrivr/cottontail/server/grpc/DQLServiceTest.kt), [DMLServiceTest.kt](https://github.com/vitrivr/cottontaildb/blob/master/cottontaildb-dbms/src/test/kotlin/org/vitrivr/cottontail/server/grpc/DMLServiceTest.kt) and [DDLServiceTest.kt](https://github.com/vitrivr/cottontaildb/blob/master/cottontaildb-dbms/src/test/kotlin/org/vitrivr/cottontail/server/grpc/DDLServiceTest.kt)
