### ISSUE TITLE
kNN Retrieval Time Increase for Complex Vectors

### ISSUE THREAD

**Issue by gabuzi** [vitrivr/cottontaildb#23]
k=1 lookup-tests with a dataset of roughly 9 million Complex32Vectors of length 20 show a great increase in retrieval time of rev. c0eb4e21 (I call it new version here) over a version based on rev. 1696878b (old version).

I tested with a query of 16384 Complex32Vectors in batches of 10000 with the CosineDistance measure. 

The current version did not return results for the first 10000 Vectors after 7 h while the old version returned results for the entire query set after approx 2.5 h.

Insertion times for the 9 million vectors are also increased for the new version (ca 30 min vs. ca 12 min).

All tests were run on a 13" MacBook Pro from 2015 with 16 GB of RAM and a Core i5-5287U CPU @ 2.9 GHz.

**Comment by gabuzi** [comment]
I did additional tests with only 11 and 2 query Vectors to show that the new version eventually completes the retrieval. Retrieval Times are:
11 Vectors:
* c0eb4e2: 214 s
* 1696878: 6 s

2 Vectors: 
* c0eb4e2: 45 s
* 1696878: 17 s

**Comment by ppanopticon** [comment]
I did some improvement on the implementation of Complex32 and Complex64 values. Firstly, there are now UnitTests that should make sure correctness of the operations. Secondly, I believe I have managed to improve execution time as well.

Since Complex32Vectors and. Complex64Vectors rely on Complex32 and Complex64 for all operations, there should be a measurable effect. Can you confirm that?

**Comment by gabuzi** [comment]
With 573e30c6 I can't notice speedups, unfortunately.
* 11 vector query: 228 s
* 2 vector query: 47 s

Note: I worked with the data imported to c0eb4e2 and have not re-imported the data in the new version.

**Comment by gabuzi** [comment]
With the changes in #27, I could go down to ca 10-15s for 11 query vectors

**Comment by gabuzi** [comment]
With 8954a17c7b8707a19bddd297260fbf5947141633, I can get the following retrieval times:

* 11 vectors, cosine metric: 12 s
* 11 vectors, real inner product metric: 6 s
* 11 vectors, absolute inner product metric: 7 s

* 100 vectors, cosine: 85 s
* 100 vectors, real IP: 45 s
* 100 vectors, abs IP: 46 s

Metrics were tested for correctness against math commons lib. It seems like this problem is gone. I can imagine that there's further room for improvement for the cosine metric by not using it as an operation composed of dot divided by the l2 norms (which means 3 iterations over the vectors, one for the product and one for each vector to get the norms) but rather as a single operation.

**Comment by ppanopticon** [comment]
Fixed on dev with integration of @gabuzi's changes.
