### ISSUE TITLE
Limit is ignored for Text-Queries

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/cottontaildb#25]
Steps to reproduce: 
- Have an entity with a text column and _n_ entries
- Do a LIKE query with _n-k_ limit

You will get more than _n-k_ results if there are more than _n-k_ matches

**Comment by lucaro** [comment]
Is it ignored or is there an off-by-one error?

**Comment by silvanheller** [comment]
It is completely ignored. I updated the issue

**Comment by ppanopticon** [comment]
Is this still an issue? I believe that addressing the issue with the preview command should have fixed this as well.

**Comment by silvanheller** [comment]
This has been fixed by 5b7b287d909fd5109efc41e522281563fecf72f2, thanks!
