### ISSUE TITLE
NPEs lead to unspecific error messages during the query execution

### ISSUE THREAD

**Issue by gabuzi** [vitrivr/cottontaildb#32]
NPEs often lead to exceptions with unspecific messages in the form of "...cannot be null" caused by another NPE when trying to create an ExecutionPlanException in src/main/kotlin/org/vitrivr/cottontail/execution/ExecutionPlan.kt line 99

This seems to be a rather unspecific issue, I'm just noting it down for reference and as a reminder that we should be aware of the nullability issues, especially when using java code from kotlin (see https://kotlinlang.org/docs/reference/null-safety.html and https://kotlinlang.org/docs/reference/null-safety.html).

**Comment by ppanopticon** [comment]
This is probably fixed on dev, where the query planner has been revamped completely. Should specific NPEs occur, please open a new issue for those.
