### ISSUE TITLE
CLI Expansion

### ISSUE THREAD

**Issue by sauterl** [vitrivr/cottontaildb#35]
Collection of additional features for the (new) CLI and main discussion thread.

See the work in progress: https://github.com/vitrivr/cottontaildb/tree/feature/cli-expansion

Please comment to add other features you would like to see in the CLI!

 - [x] `table <schema> <entity>` - Tabulated presentation of preview
 - [x] `clear <schema> <entity>`  - Clears the specified entity, without actually dropping the entity
 - [ ] `create <schema> <entity> ???` - Creates the specified entity. ??? stands for the column definition, TBD
 - [x] `index` <schema> <entity> <column> <index type> - Creates an index on the given column. Also rebuilds this index
 - [ ] `use <schema>` - To set the schema and subsequent commands will use the specified schema. Not entirely sure about this one, tbh
 - [ ] TBD More flexible query as the current 'find'
 - [x] Better visualization

**Comment by lucaro** [comment]
Something like https://github.com/JakeWharton/flip-tables would be helpful for the display of returned results.

**Comment by gabuzi** [comment]
Listing of existing indexes and dropping them would be nice to have

**Comment by ppanopticon** [comment]
On dev, there is now a DELETE and TRUNCATE gRPC endpoint, which can be used to implement the ``clear <schema> <entity>`` command.

**Comment by silvanheller** [comment]
Just here to second @gabuzi's suggestion to list indexes for entities

**Comment by ppanopticon** [comment]
Tabulated preview of entity content is now default (--> dev).

**Comment by sauterl** [comment]
Added index related commands (on `dev`)

**Comment by silvanheller** [comment]
I'd avocate closing this issue and merging the existing CLI improvements into dev. The three open points are all unclear and are probably better suited for a discussion

**Comment by sauterl** [comment]
The merging happened a long time ago and thus I close this issue for now.
