### ISSUE TITLE
Tests not successfully running on dev

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/cottontaildb#42]
There are currently a number of tests not working on dev:

* Running the `MappedFileChannelStoreTest` leads to a deadlock while growing the store.
* testL2Distance() and testL2SquaredDistance() fail in the IntVectorDistanceTest
* the `UniqueHashIndexTest` fails because of the changed name-handling.
* and some of the complex vector tests fail but that is to be expected i guess since @gabuzi is actively working on those.

**Comment by ppanopticon** [comment]
Resolved!
