### ISSUE TITLE
IN Clauses cause LIKE operator to not work

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/cottontaildb#43]
As an example, consider the query in the appendix (which has a rather large in-clause, but that should not matter)
[in-like.proto](https://github.com/vitrivr/cottontaildb/files/5039904/in-like.txt).

The use-case is rather straightforward: We're doing staged queries and the second stage is text

**Comment by ppanopticon** [comment]
This should be fixed on the dev-branch. Can you confirm?

**Comment by silvanheller** [comment]
Yes, thanks!

**Comment by ppanopticon** [comment]
For future reference: [in-like.proto.zip](https://github.com/vitrivr/cottontaildb/files/5594930/in-like.proto.zip)
