### ISSUE TITLE
db stopping directly after start

### ISSUE THREAD

**Issue by mpas97** [vitrivr/cottontaildb#47]
Since commit 1241e4b0f00111db3551fdfa39921642f6e9219a I'm not able to run cottontaildb anymore. Not locally, nor it works on the server. There is no error, it just starts up then shutsdowns directly and terminates with build successful. Any ideas?
<img width="629" alt="grafik" src="https://user-images.githubusercontent.com/9994218/93199791-1f6dfb80-f74f-11ea-8c1a-6a980f5da7ed.png">
(Gradle version installed is 6.x, so the 7.x warning can not be the cause.)

**Comment by sauterl** [comment]
As far as I'm aware, the new CLI only works when **not** using `gradle run`. Did you try to build an executable JAR and run it?
This works in all use cases I've had lately.

The task for the executable JAR is `./gradlew shadowJar`

**Comment by mpas97** [comment]
Hm okay.. the point is that the only changes in this commit are [these.](https://github.com/vitrivr/cottontaildb/commit/1241e4b0f00111db3551fdfa39921642f6e9219a?w=1)
But with the commit before the mentioned one as well as further backwards everything works fine. So I will build the jar, zip or whatever :)

**Comment by mpas97** [comment]
Anyway, `./gradlew shadowJar` is never mentioned in the readme but `./gradlew run` is.

**Comment by sauterl** [comment]
Personally, I usually generate a distribution zip (`./gradlew distZip`), unzip it and use the created `cottontaildb` executable to run cottontail

Did you succeed with the JAR or is it still not working as intended?

**Comment by mpas97** [comment]
I went the way with the zip too, that's working.

**Comment by silvanheller** [comment]
So we have multiple issues: (i) `./gradlew run` instantly quits. (ii) `./gradlew jar` exits with 
```
no main manifest attribute, in build/libs/cottontaildb-1.0-SNAPSHOT.jar
```
