### ISSUE TITLE
table CLI command crashes when no elements are present in the table

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/cottontaildb#50]
Would still be useful to see the schema.
Reproduce:
- Create empty entity.
- `table $schema $entity`
- crash

**Comment by ppanopticon** [comment]
master or dev?

**Comment by silvanheller** [comment]
master, sorry

**Comment by ppanopticon** [comment]
Maybe I'm too stupid but there seems to be no ``table`` command on master (which makes my initial inquiry obsolete, sorry for that).

I could reproduce the error on _dev_ though.

**Comment by ppanopticon** [comment]
Is this still an issue?

**Comment by sauterl** [comment]
On master, this looks good to me, so it could be closed.
