### ISSUE TITLE
When building and starting cotton dB, about bin / cottontail dB / path / to / your/ config.json The command could not find the target path bin / cottontaildb

### ISSUE THREAD

**Issue by zh57398** [vitrivr/cottontaildb#51]
bin/cottontaildb /path/to/your/ config.json is a command to run at the terminal? Why can't I find the directory bin / cottontaildb, file config.json Is it located under the cottontaildb project folder config.json Documents? /Path / to / your / has changed to your own path.bin/cottontaildb /path/to/your/ config.json Is this a command to run at the terminal? Why can't I find the directory bin / cottontaildb, file config.json Is it located under the cottontaildb project folder config.json Documents? /Path / to / your / has changed to your own path.An attempt to put the cottontaildb project in the / bin folder also failed.

**Comment by ppanopticon** [comment]
In order to use the command ``bin/cottontaildb`` must first build the Cottontail DB distribution using Gradle, i.e. ``./gradlew distTar``, the _untar_ that distribution and ``cd`` into the distribution folder.
