### ISSUE TITLE
when i use Cottontail DB Docker Container ,excuting the order that  docker run --name cottontaildb -p 1865:1865 -v /path/to/volume:/cottontaildb-data docker.pkg.github.com/vitrivr/cottontaildb/cottontaildb:<version>,the result of  command  is  Unable to find image 'docker.pkg.github.com/vitrivr/cottontaildb:latest' locally. So  what should i do ?

### ISSUE THREAD

**Issue by Yaixi** [vitrivr/cottontaildb#52]

**Comment by ppanopticon** [comment]
You need to login into GitHub in order to be able to download the Docker image. See official [manual](https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-docker-for-use-with-github-packages) for further information

**Comment by Yaixi** [comment]
I logined  docker.And i excuted the order that  docker run --name cottontaildb -p 1865:1865 -v /home/yaixihn/vitrivr/cottontaildb:/cottontaildb-data docker.pkg.github.com/vitrivr/cottontaildb/cottontaildb:0.8. Still the same error.The command has an error?

**Comment by ppanopticon** [comment]
You're missing a v in the version. I.e. v0.8 instead of 0.8

**Comment by zh57398** [comment]
There is still this error. It is not allowed to write release V0.8 instead, and the V0.8 part will be ignored automatically, as if only "release" was read.

**Comment by zh57398** [comment]
There is still this error. It is not allowed to write release V0.8 instead, and the V0.8 part will be ignored automatically, as if only "release" was read.

**Comment by ppanopticon** [comment]
The command ``docker run --name cottontaildb -p 1865:1865 -v /Users/rgasser/Downloads/data:/cottontaildb-data docker.pkg.github.com/vitrivr/cottontaildb/cottontaildb:v0.8`` works perfectly on my machine.

Usually, Docker reports that it can't find the image locally (as reported by you) and then starts downloading the image from GitHub. Can you give me more information (such as a screenshot) as to what doesn't work for you?

**Comment by ppanopticon** [comment]
I suppose you were able to resolve this issue.
