### ISSUE TITLE
exception in thread "main" java.nio.file .NoSuchFileException: /cottontaildb-data/ config.json

### ISSUE THREAD

**Issue by zh57398** [vitrivr/cottontaildb#53]
I found the image now, but he told me that I didn't have a config file. The error is: exception in thread "main" java.nio.file .NoSuchFileException: /cottontaildb-data/ config.json
I put the configuration file of cottontaildb in / cottontaildb data or / users / rgasser / downloads / data / cottontaildb data. Someone encountered a similar error. He thought it was a permission problem, and he copied the missing file to the corresponding path of the host in docker to solve the problem. However, I did similar operations and did not solve the problem. Here, Co What is the nfig file? How can I solve this problem?

**Comment by ppanopticon** [comment]
Cottontail DB in the Docker container is looking for a config file under ``/cottontaildb-data/config.json``(in the container).

Hence, you must make sure that the _config.json_ file is located in the folder you're mapping with the ``-v`` argument. For example, if you're mapping the volume with ``-v /path/to/volume:/cottontaildb-data``, then you must place the ``config.json`` under ``/path/to/volume/config.json`` (on the host).

Obviously, it is also important that you map the volume to ``/cottontaildb-data``. Furthermore, the ``root`` setting in the config.json file should point to a location relative to ``/cottontaildb-data`` (e.g.  ``/cottontaildb-data/data``)

**Comment by ppanopticon** [comment]
Hey! Were you able to solve the issue?
