### ISSUE TITLE
Repairing Indices / Dropping them when they're not present anymore

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/cottontaildb#57]
Currently, if something goes wrong with the file-system (e.g. you delete `index.db` or one of the index files under an entity), you cannnot drop an index which is not present anymore since cottontail crashes while loading the entity.
Ideally, dropIndex() would cause entity headers to drop the index also if it is not present anymore.
Even if you delete the whole folder of the entity, you can't drop it anymore, since it tries to drop associated index structures first (which are of course not present anymore)

**Comment by ppanopticon** [comment]
I cannot reproduce the issue.

I have run several tests now with different index structures (namely, _NonUniqueHashIndex_, _UniqueHashIndex_ and _LuceneIndex_). And for all of them, if I manually delete the index files in the filesystem and then try to either optimize or drop the index, Cottontail DB re-creates the missing files.

Can you provide me with more details on this?

**Comment by silvanheller** [comment]
I think it's related to #58 - seems to be another windows-issue. I'll close and re-open another issue if i can reproduce it on a unix system
