### ISSUE TITLE
Performance for queries with large IN-Clauses / Parallelization

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/cottontaildb#61]
Observing Cottontail’s performance during Cristina Illi’s MSc Thesis it seems to me that cottontail does not utilize parallelization for queries which require index scans / full table scans or there is something broken about my index configuration for non-unique hash indices / non-unique hash index performance.
In particular, when utilizing the current VBS-Dump (https://download-dbis.dmi.unibas.ch/vitrivr/cottontaildb-data-descriptions-201125.zip), queries with 20-30k elements in the IN-Clause for the `id` column on the largest table (features_segmenttags) can take up to three minutes of execution time during which all cpu cores except one idle.
I’m not sure if parallelization is the fix for this or if there are other issues here.

**Comment by ppanopticon** [comment]
Currently, only kNN queries are parallelised. We could add this for Boolean queries, of course, especially when full table scans are involved. However, 3 minutes for this IN-clause with index sounds like an awful lot to me.

**Comment by ppanopticon** [comment]
I ran a few tests (on my machine): _SELECT * FROM cineast.features_segmenttags WHERE id IN X_. In my test, X had 10000 entries. The entity _features_segmenttags_ contains 31182895 rows.

On _master,_ this query takes:

**Brute force:** ~12s
**Indexed (Non unique hash index):** ~5s

With a few optimizations on  _dev_, the same query now takes:

**Brute force:** ~12s
**Brute force (parallelised):** ~12-14s
**Indexed (Non unique hash index):** ~1.5s

Apart from replacing the storage engine, which is something we're working on, there are only minor things that can be optimised in the brute-force case. It seems, though, that parallelisation does not really help here. The time we're observing is really the time it takes to iterate through the 31 million rows, hence, I assume that the workload is pretty much IO bound. This is especially true as disk access gets more expensive.

Just as a comparison: If you run the query SELECT * FROM cineast.features_segmenttags WHERE id = X (now X is just some value), then we see the following results:

**Brute force:** ~10-11s
**Indexed (Non unique hash index):** ~500ms

**Comment by silvanheller** [comment]
Thanks for having a look! so i guess we'll write this off as querying 30 million rows on an HDD is a bad idea and it's also a bad idea to send all of the results over the network (since we're actually more interested in `SELECT COUNT(*), tagid FROM table WHERE id in X GROUP BY tagid`)
