### ISSUE TITLE
Entity optimization not persistent

### ISSUE THREAD

**Issue by lucaro** [vitrivr/cottontaildb#67]
When optimizing an entity, such as to rebuild an index, the changes are not persisted and disappear after a restart. This is true for at least the non-unique hash index, other indices have so far not been tested. This behaviour was observed on the dev branch, as of version https://github.com/vitrivr/cottontaildb/commit/108552b7b3e7c8a5cbead1e0eff51442b91c5fa7.
Steps to reproduce:

1. create an entity
2. fill entity with data
3. create non-unique has index (which is not initialized, despite `setRebuild(true)` )
4. query entity --> there are no results returned since the index is used despite it being empty
5. optimize entity via the CLI
6. query entity --> the query now returns results
7. stop cottontail via the CLI and start it again
8. query entity --> there are again no results

**Comment by ppanopticon** [comment]
Should be fixed on dev.
