### ISSUE TITLE
Publish Cottontail Docker-container on Dockerhub

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/cottontaildb#70]
Currently, our docker container is only available on Github. This means you need to authenticate with a personal token to pull it, which is suboptimal for shared machines (and also in general, since it's effort for every new machine you set up).

Ideally, we would simply also publish the container on dockerhub, like we do with Cineast.

**Comment by ppanopticon** [comment]
Done! Cottontail DB is now available on DokckerHub.

``docker run -it --name cottontaildb vitrivr/cottontaildb:latest``
