### ISSUE TITLE
nullable property for entity columns 

### ISSUE THREAD

**Issue by ronic09** [vitrivr/cottontaildb#84]
Hello! Me again :)
Cottontail provides a "nullable" property in the column definition of an entity. 
I am now trying to figure out how I can insert an entry with a "NULL" value for a column with the property "nullable=True".
However, cottontail always responds with an error, mostly something like: "INSERT failed because of a database error. A value of NULL cannot be cast to INT."

Environment: 
- cottontail-db Version: 0.12.11
- cottontail-python-client Version: 0.0.4 (Built with Cottontail DB Proto version 0.12.2) 

Examples of what I've tried so far: (column 'count_category' is defined as 'column_def('count_category', Type.INTEGER, nullable=True)'
(i) entry = {'count_category': Literal(intData=None)}
(ii) entry = {'count_category': Literal(nullData=None)} 
(ii) omit the column specification for 'count_category' from the insert specification

Do you have any idea what I am doing wrong? Is this feature already supported? Might the problem be caused by the cottontail-python-client?

Many thanks for your help!
Best Simon

**Comment by ronic09** [comment]
Thank you for your reply. Shall I open a new issue in the cottontail-python-client repository or will you come back to me as soon as you got an answer from your colleague?

**Comment by Spiess** [comment]
I have just tested this, and in my minimal setup and with the latest Cottontail DB it works the way @ppanopticon has described.

To make working with Null values more convenient I just updated the Cottontail DB Python Client to allow importing the Null message object directly from the cottontaildb_client module. (This change is currently only on the main branch of the git repository, and will only appear in the pypi package in the next release)

I have also updated the README usage example with a Null value usage.
Please let us know if this works for you and if we can close the issue.

**Comment by ronic09** [comment]
Hello. It works! Many thanks for the hint and please excuse the effort I have caused you

**Comment by Spiess** [comment]
No problem, always happy about feedback 👍
