### ISSUE TITLE
Fork / move this repo to the vitrivr umbrella 

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/cottontaildb#9]
Using [the official guide](https://help.github.com/en/articles/transferring-a-repository#transferring-a-repository-owned-by-your-organization), we should transfer this repo to the vitrivr org. This simplifies access rights, but allows access to things like CI builds etc. for all contributors.

**Comment by lucaro** [comment]
I would very much argue for a transfer and against a fork, it would be clearer this way.

**Comment by ppanopticon** [comment]
Done!
