### ISSUE TITLE
Error message on the Windows terminal when using the executable distribution

### ISSUE THREAD

**Issue by benzvera** [vitrivr/cottontaildb#92]
Hi, 
I built an executable distribution of Cottontail DB by using the Gradke task `distZip`. Afterwards, I tried starting it by executing `bin\cottontaildb.bat config.json`. The only response my Windows terminal gave me was: "Die eingegebene Zeile ist zu lang. Syntaxfehler." 
If I start Cottintail DB via the executable JAR, there is no problem.

**Comment by ppanopticon** [comment]
Hey Vera

Thanks. Basically, this is a known issue and can be attributed to a restriction of _cmd.exe_ and the allowed length of commands. Am I assuming correctly, that you're using _cmd.exe_?

Where is Cottontail DB located?

Best,
Ralph

**Comment by benzvera** [comment]
Hi Ralph, 

Yes, I am using _cmd.exe_ and I have cloned Cottontail DB to my laptop. 

Best, 
Vera

**Comment by benzvera** [comment]
Hi Ralph, 

Yes, I am using _cmd.exe_ and I have cloned Cottontail DB to my laptop. 

Best, 
Vera

**Comment by benzvera** [comment]
Hi Ralph, 

Yes, I am using _cmd.exe_ and I have cloned Cottontail DB to my laptop. 

Best, 
Vera

**Comment by ppanopticon** [comment]
Yes but what folder? It may help to move everything to a top-lvl, e.g., C:\ since the issue is the length of all the different paths.

**Comment by benzvera** [comment]
I have it in _...\Desktop\UniBas\6_Semester\Bachelorarbeit_. I tried moving it to C:\ but I still get the same error.

**Comment by benzvera** [comment]
The issue is resolved with the newest update.
