### ISSUE TITLE
Limit option bugged for Preview

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/cottontaildb#97]
To reproduce on any table which contains data:

`query preview -l 2 entity`

and see how more than 2 results come back (this also holds for 3, 4 etc.)

**Comment by ppanopticon** [comment]
I cannot reproduce this issue.  It seems to work as expected for my V3C1 collection with the current _master_ version of Cottontail DB.

Can you provide me with more information (e.g., OS, name of the entity etc.)?

**Comment by silvanheller** [comment]
On 2 ubuntu machines with the most recent `master` commit (i.e. 0eac5334d98dacbc2272d50b346af3030df89a8e), 
```
query preview -l 2 cineast.features_visualtextcoembedding 
```

Funnily enough, not all entities exhibit this behavior, e.g. `cineast_multimediaobject` and `cineast_segment` and `cineast_mediancolor` do not. 

`features_ocr`, `features_ehd` also return too much lines.

**Comment by ppanopticon** [comment]
Found the issue and applied a fix.

A more sustainable solution should be created as part of #98
