### ISSUE TITLE
ImportCommand should use BatchImport

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/cottontaildb#99]
The current ImportCommand implementation does not use BatchImport which is performance-wise suboptimal.

**Comment by ppanopticon** [comment]
While I agree that this is a desirable optimization, I must nevertheless ask: Have you tried the `-t` (single transaction) option for the import command?

**Comment by silvanheller** [comment]
No updated in #96, that's indeed faster. Should've read the documentation...
